version: '3'
services:
  postgres:
    image: postgres:9.4.24
    container_name: starseeker-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      PG_USER: postgres
  mongo:
    image: mongo:3.6.12
    container_name: starseeker-mongo
    volumes:
      - mongo-data:/var/lib/mongodb/data
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: starseeker
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo
    environment:
      DATABASE_HOST: postgres
      MONGO_HOST: mongo

volumes:
  postgres-data:
  mongo-data:
