version: '3'
services:
  postgres:
    image: postgres:9.4.24-alpine
    container_name: starseeker-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      PG_USER: postgres
  mongo:
    image: mongo:4.4.1
    container_name: starseeker-mongo
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
  redis:
    container_name: starseeker-redis
    image: redis:5.0.4-alpine
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: starseeker
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo
      - redis
    environment:
      DATABASE_HOST: postgres
      MONGO_HOST: mongo
      REDIS_URL: redis://redis:6379
      BUNDLE_PATH: /bundle
      BASE_URL: ${BASE_URL:-http://localhost:3000}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_LOGIN: ${GITHUB_LOGIN}
      GITHUB_SECRET: ${GITHUB_SECRET}
      GITHUB_TOKEN: ${GITHUB_TOKEN}

volumes:
  postgres-data:
  mongo-data:
  mongo-config:
  bundle:
