default: &default
  adapter: postgresql
  user: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: starseeker_development

test:
  <<: *default
  database: starseeker_test

production:
  database: starseeker_production
