name: reviewdog
on: [pull_request]
jobs:
  brakeman:
    name: runner / brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
      - name: brakeman
        uses: reviewdog/action-brakeman@v2
        with:
          brakeman_version: 4.8.2
          reporter: github-pr-review # Default is github-pr-check
