name: Reviewdog

on: [pull_request]

jobs:
  brakeman:
    name: brakeman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
      - uses: reviewdog/action-brakeman@v2
        with:
          reporter: github-pr-review # Default is github-pr-check
