name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.4
        env:
          POSTGRES_PASSWORD: password
      redis:
        image: redis:7.0
        options: --entrypoint redis-server

    container:
      image: ruby:3.4.7
      env:
        BASE_URL: 'http://example.com'
        DATABASE_URL: postgresql://postgres:password@postgres
        RAILS_ENV: test
        REDIS_URL: redis://redis:6379
        RUBYOPT: '-W:deprecated'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set without 'development production'
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Setup
        run: |
          bin/rails db:create db:migrate
      - name: Run specs
        run: |
          bundle exec rake
